Feature/ItemRenting-111-mk
Pyragas/tool-rent pull request #37
Opened 2021-05-13 13:19 UTC by kryzma

2021-05-13 15:46 UTC, gintunas requested changes
Added comments what to change.
One more note for the future - good practice is to avoid camelCase in branch naming. Use hyphens and all letters lowercase.

2021-05-13 15:46 UTC, gintunas commented on src/main/java/com/psk/pyragas/ToolRent/usecases/ExampleItem.java
> +        return "index.xhtml";
Probably should add ?faces-redirect=true

2021-05-13 15:46 UTC, gintunas commented on src/main/webapp/add_item.xhtml
> +            <br/>
Just general note to the future - it is better to avoid br in styling. Add css with layout spacing.

2021-05-13 15:46 UTC, gintunas commented on src/main/webapp/example_item.xhtml
> +                <p:tab title="Uzsakymo detales">
Write with Lithuanian letters if it is visible to user.

2021-05-13 15:46 UTC, gintunas commented on src/main/webapp/example_item.xhtml
> +            <br/><label>Naudojimo pradzia</label>
Same here - needs lithuanian letters

2021-05-13 15:46 UTC, gintunas commented on src/main/webapp/other_profile.xhtml
> +                <h3>Email: #{otherProfile.profile.email}</h3>
It should be in Lithuanian, not English.

2021-05-13 20:28 UTC, kryzma commented
> Added comments what to change.
> One more note for the future - good practice is to avoid camelCase in branch naming. Use hyphens and all letters lowercase.

If Epic of task has multiple words then branch will look something like:
"feature/make-this-thing-work-188-mk"
It is not so easy to tell apart which part of branch name is telling about Epic or which part is just Jira's task Id.
In other words, Epic name, Jira id and creator's name melt into one blob.

2021-05-14 08:32 UTC, gintunas commented
Yes it may be the case. But one more good practice is to avoid too long descritptive names.
I used this guide for naming https://codingsight.com/git-branching-naming-convention-best-practices/
I think if word is very long, we could separate it with underscores _.

Good thing to avoid camelcase is because some systems are case insensitive, some are case sensitive and there's ambiguity in branch's name.,

2021-05-14 08:38 UTC, gintunas approved these changes

2021-05-14 08:38 UTC, gintunas commented on src/main/webapp/example_item.xhtml
> -                <p:tab title="Uzsakymo detales">
One ž letter left, but it's good enought for now😆

2021-05-14 09:14 UTC, merged